# Generated by Django 4.2.11 on 2024-05-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkinVisionApp', '0002_annotation_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='label',
            new_name='image_data',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='data',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='image',
        ),
    ]
